### ISSUE TITLE
mqsqli database ?

### ISSUE THREAD

**Issue by alidz1982** [IamSadiq/howfar#1]
please..upload all the script...

**Comment by IamSadiq** [comment]
It's a work in progress, that's all the scripts for now.. Unless you mean i should export my SQL and include it .

**Comment by IamSadiq** [comment]
I just added "sql-script/magana.sql", so check it out. I hope that helps.

**Comment by alidz1982** [comment]
thanks man...

**Comment by IamSadiq** [comment]
You're welcome
